import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const watch = (process.argv[2] === "--watch");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		// Note: ical.js and chrono-node must be bundled, not externalized
		// Dynamic imports in Obsidian only work with bundled code
		...builtins
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	metafile: true,
});

if (watch) {
	await context.watch();
} else {
	const result = await context.rebuild();

	// Write metafile for bundle analysis
	if (result.metafile) {
		const fs = await import('fs');
		fs.writeFileSync('meta.json', JSON.stringify(result.metafile));

		// Calculate and display bundle sizes
		const outputs = result.metafile.outputs;
		console.log('\n📦 Bundle Analysis:');
		for (const [file, output] of Object.entries(outputs)) {
			const sizeKB = (output.bytes / 1024).toFixed(2);
			console.log(`  ${file}: ${sizeKB} KB`);

			if (output.inputs) {
				const sortedInputs = Object.entries(output.inputs)
					.map(([path, info]) => ({ path, bytes: info.bytesInOutput }))
					.sort((a, b) => b.bytes - a.bytes)
					.slice(0, 10);

				console.log('  Top 10 largest dependencies:');
				sortedInputs.forEach(({ path, bytes }) => {
					const kb = (bytes / 1024).toFixed(2);
					console.log(`    ${kb} KB - ${path}`);
				});
			}
		}
	}

	process.exit(0);
}
